### ISSUE TITLE
[Request] Translation Option

### ISSUE THREAD

**Issue by bookerthegeek** [dsp-mod/StarMapTools#1]
## Heyo! ##

Love the idea of this mod. Sadly as I can only read English, the usability of it is a little bit out of reach for me. Would it be possible to add in an ability to select the display language either in game or in the config file?

### Thank you ###
Keep up the great work!

**Comment by skyatgit** [comment]
ok,i will do it

**Comment by skyatgit** [comment]
Now support English @bookerthegeek

**Comment by bookerthegeek** [comment]
Thank you!

**Comment by bookerthegeek** [comment]
Stupid question... How do I switch it to English? I'm using version 3.0.3

**Comment by skyatgit** [comment]
download v3.2 from github

**Comment by skyatgit** [comment]
https://github.com/dsp-mod/StarMapTools/releases/download/v3.2/StarMapTools.zip @bookerthegeek
